apiVersion: v1
kind: Pod
metadata:
  name: ingot
  namespace: gold
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: 200Mi
        limits:
          memory: 500Mi
